# Generated by Django 3.1.5 on 2021-02-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210201_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.TextField(null=True),
        ),
    ]
