# Generated by Django 3.1.5 on 2021-02-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_sessions',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
