# Generated by Django 3.1.5 on 2021-02-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_sessions_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_sessions',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user_sessions',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
